### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by alganthe** [alganthe/MFFA#1]
## **high**
- [x] Add CBA and XEH support.
- [x] finish the takistani insurgents opfor
- [x] Port the takistani insurgents to Indep
## **medium**
- [x] Change the name to MFFA (More Factions For Arma3).
## **low**
- [x] Add a logo and picture.
