### ISSUE TITLE
PMC faction

### ISSUE THREAD

**Issue by alganthe** [alganthe/MFFA#17]
## 1. TODO
- [ ] Branch off
- [ ] Prepare the layout
- [ ] Unit 
  - [ ] Classnames
  - [ ] Configs
  - [ ] Test, check for config misshaps
- [ ] Loadouts
  - [ ] Test
- [ ] Repeat all steps above for the indep variant
- [ ] Merge into master
