### ISSUE TITLE
Russian rebels TODO list

### ISSUE THREAD

**Issue by alganthe** [alganthe/MFFA#9]
## Blufor variant
- [x] Units
- [x] Groups
- [x] Identities (inherited from RHS)
- [x] Uniforms and backpacks
## Indep variant
- [x] Port the blufor variant to indep
## Polishing
- [x] Facewear and headgear 
- [x] randomization + EH
- [x] Flag
